### ISSUE TITLE
wrong gas consumption per degree day

### ISSUE THREAD

**Issue by mourmeer** [Ernst79/degree-days#12]
how can I compensate for the initial gas meter reading on Jan 1st? I think it just uses the meter reading.
I do not have a sensor for consumption only a gas meter reading since installation of the gas meter.

**Comment by Mark-LogiQ** [comment]
You can add a utility meter sensor.
Go to - Settings - Devices and Services - Tab "Helpers" - Bottom Right "Create Helper".
Select - Utility Meter - For Input Sensor fill in your gas meter - for Meter Reset Cycle fill in Yearly.

**Comment by MarkyMarkNL** [comment]
You can add a utility meter sensor.
Go to - Settings - Devices and Services - Tab "Helpers" - Bottom Right "Create Helper".
Select - Utility Meter - For Input Sensor fill in your gas meter - for Meter Reset Cycle fill in Yearly.
