### ISSUE TITLE
Degree days integration will failfrom 2023.3 on....

### ISSUE THREAD

**Issue by Koen010** [Ernst79/degree-days#13]
Hi Ernst, my HA gives me this wearning in the log. As a rabid user of the degree days integration, I would kindly ask you if you would be willing to look into this?
"Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for degree_days using this method at custom_components/degree_days/__init__.py, line 41: hass.config_entries.async_setup_platforms(entry, PLATFORMS)"

**Comment by Ernst79** [comment]
Will look into it.

**Comment by Ernst79** [comment]
Should be solved with 0.9.0.
