### ISSUE TITLE
Sensor for current year gas consumption

### ISSUE THREAD

**Issue by 0000vt** [Ernst79/degree-days#22]
As you mention in the readme, a Gas sensor entity with the total consumption this year should be feeded to the integration.

Is this a sensor of the last 365 days? Or a sensor from the 1st of january? What is needed by the integration?

**Comment by Ernst79** [comment]
You will need a sensor that reports the total amount of gas starting from the start date that you specify in the settings of the integration. You can e.g. use a utility meter in HA to generate a sensor with the year total starting at 1-januari (or a different date, by setting an offset). See https://www.home-assistant.io/integrations/utility_meter/

You can use that sensor as input for degree-days and set the start date to the same date as your utility meter sensor.

**Comment by Ernst79** [comment]
Please note that 0.9.3 has a small error when adding a new sensor, 0.9.4 should fix it

**Comment by 0000vt** [comment]
Ok, thats what i had since november with the offset built in. But now the weighted degree days are reset since yesterday due to the new year. Because the degree days stayed around 2300 and the consumption got to zero.

**Comment by Ernst79** [comment]
Not sure I understand it right, but assuming your gas sensor is reporting the total from 1 November
- your gas sensor should report the total m3 of gas since 1 November  (so your gas consumption sensor should not be reset on 1 January)
- The start day should be 1 and the Startmonth should be November in the degree days integration. 

Is that what you use?

**Comment by 0000vt** [comment]
Oh I get it. I had the yearly utility meter started in november, but it resets 1st of january. Thats two different offsets. Anyway, got to start from 1st of january now since the sensor had some weird data now.

Thanks for the explanation.

**Comment by Ernst79** [comment]
Yep, then change the Startday to 1 and the Startdate to January.
