### ISSUE TITLE
icoon in HACS?

### ISSUE THREAD

**Issue by Xander-V** [Ernst79/degree-days#26]
Hi Ernst, leuk idee dit, hoop dat je integratie blijft werken en super dat je hem al zo hebt opgezet dat hij al in HACS past! Volgende stap natuurlijk dat hij niet meer custom hoeft te worden toegevoegd, maar automatisch in HACS komt én dat je dan ook een icoontje toevoegt :) Zie dat je er nu nog geen een hebt, in de lijst van HACS komt er daarom alleen een "image not available" bij de verwijzing (https://brands.home-assistant.io/_/degree_days/dark_icon.png) en daardoor zie je in bijvoorbeeld het repairs scherm niet waar het over gaat:

![image](https://github.com/Ernst79/degree-days/assets/97856913/6e2a99d4-211b-461e-8509-ff4fd670bce3)

Voor meer info over hoe je je eigen icoon toevoegt, zie https://github.com/home-assistant/brands/tree/master/custom_integrations/

Thx man, ik ga  er binnenkort eens mee stoeien!

**Comment by Ernst79** [comment]
Klopt, moet hem ook nog eens verplaatsen naar de officiële HACS custom components directory.

**Comment by Ernst79** [comment]
Icoon is geüpload en gemerged https://github.com/home-assistant/brands/pull/5064
