### ISSUE TITLE
For Newbies

### ISSUE THREAD

**Issue by nielswest65** [Ernst79/degree-days#6]
Could you give us /me :-) examples to copy how this integration works? I installed it using HACS this worked, but no sensors where made? I know, I shouls probelbly know how to. but I did not chose a UI system for the fun off it. I like things going by itself? or other people making it easy for me ;-). I am not a coder.

**Comment by Ernst79** [comment]
Did you configure the integration? Like this? 

![image](https://user-images.githubusercontent.com/24375847/148113777-fb5813f7-3ff5-4fe5-9a0d-9c96079bfb40.png)

Sensors should show up automatically, if not, you have found a bug. :-)

**Comment by nielswest65** [comment]
No could not find the sensors, did these values in the const.py file? this did not show. tried to put the sensors manualy in config.yaml. got errors.
this my system?

![image](https://user-images.githubusercontent.com/75585354/148119234-e85b90d5-abc9-4cb1-a9c2-114b058fbd3b.png)

bug could be newbie error though :-) 
logbook details:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:164
Integration: Sensor (documentation, issues)
First occurred: 20:08:38 (4 occurrences)
Last logged: 20:08:38

The degree_days platform for the sensor integration does not support platform setup. Please remove it from your config.

**Comment by Ernst79** [comment]
You can’t use yaml to configure the component, only configuration in the UI., can you show a printscreen of your configuration?

**Comment by jeffreyveldt** [comment]
First of all, many thanks for making this. (and sorry for highjacking the topic)

I got the integration working had some prerequisites i had to figure out first. 
- yearly gas sensor <- maybe we can piggyback on the energy dashboard? I had to create a new utility sensor now.  
- degree days starts with the year 2021, not the current year. (this is hardcoded) when initializing. My yearly gas starts from jan 4th currently, so i had to change the 2021's to 2022 in the .py files using visual code studio. 

Hacs installation is not hard but you have to know how hacs works. Hacs gives a new integration for degree days. 
So 
step 1: install degree days via hacs
step 2: reboot
step 3: In HA goto config -> integrations. add degree days integration there. 
step 4: in dashboard add a card with the degree days entities.

**Comment by Ernst79** [comment]
Thanks, added the installation instructions on the main page.

- 2021 should not be hardcoded, I will look into that.
- I will look into the yearly gas sensor, not sure if we can use the energy dashboard, as I don't think these values in the dashboard are actual entities. The issue I had is that if you start with a gas sensor that represents the total, it doesn't know the value at the beginning of the year. Just like the energy dashboard, it won't be able to display data from before you have set up the dashboard, even if you have these values from somewhere else.

**Comment by jeffreyveldt** [comment]
idea: (but this works in my case since my measurements go from jan 1rst - dec 31ste)
Let the integration create its own yearly.gas.sensor utilitymeter. 
That way it should be able to always start from the moment the integration is added (or +1 day)

And in my case:
i just created a workaround (which only should be necessary for the 1rst year since the yearly.gas utility meterd resets on jan 1rst anyway) a sensor based on (the total gas consumption - total gas consumption 31ste dec 2021). And a reminder that a should change the gas sensor entity on jan 1st 2023 to the utilitymeter one.

`#gasyearly2022 
  - platform: template
    sensors:
      yearly_gas_2022:
        unit_of_measurement: m³
        value_template: >
          {% set totaal = states('sensor.gas_consumption') | float %}
          {% set eindjaar = 5334 | float %}
          {{ ((totaal - eindjaar)) | round(2) }}`

**Comment by nielswest65** [comment]
It was newbie error, sorry. Other HACS integrations (afvalwijzer) had me put sensors in manualy and I expected all HACS to work this way. I followd jeffreyveldt steps. and found the integration, as I did put my values as defautl everthing was correct. Now I have 4 entities . Challenge is to follow the above notes, as i put my sensor.gas,consumption as sensor and i now read this is not correct :-).

**Comment by Ernst79** [comment]
I think @jeffreyveldt has a split up configuration over several yaml files.  Try this (not tested)

```
template:
  - sensor:
      - name: "yearly_gas_2022"
        unit_of_measurement: m³
       state: >
          {% set totaal = states('sensor.gas_consumption') | float %}
          {% set eindjaar = 5334 | float %}
          {{ ((totaal - eindjaar)) | round(2) }}
```

**Comment by nielswest65** [comment]
Hi, sorry to bother you more. the sensor works and the value seems correct of course I changed the eindjaar value :-) 
![graaddagen fout](https://user-images.githubusercontent.com/75585354/148279806-d640f011-e3b0-42c8-a623-ec701428b226.jpeg)

![graaddagen config](https://user-images.githubusercontent.com/75585354/148279826-617dc82e-aec8-459f-82f7-d27b421a6d48.jpeg)

![graaddagen sensor](https://user-images.githubusercontent.com/75585354/148279858-4fe3be22-be7d-4201-9faa-61adcddbe5bf.jpeg)

**Comment by Ernst79** [comment]
For the Gas sensor entity, you have to use `sensor.yearly_gas_2022` (you forgot the `sensor.`

**Comment by nielswest65** [comment]
thanks changed it to sensor. I will now wait if values reset! have a good night

**Comment by nielswest65** [comment]
Hi,

it works, now I have to understand te values,
if i summit the same values in Mindergas. I get values I think are "correct" and the values in HA look high in degreedays, and the usage for degreedays, looks low. I live in a corner house (partialy flatroofed.) and a lot of outerwalls? probably wait a couple off month to see how it evolves. 
thanks for all your help


![image](https://user-images.githubusercontent.com/75585354/148429853-0ae7b273-299d-4f2e-8a0a-a8b4256b1b09.png)

![image](https://user-images.githubusercontent.com/75585354/148429887-9794b872-7e0b-4007-a08f-255e1fd5c7dd.png)
