### ISSUE TITLE
Add possibility to register in kWh

### ISSUE THREAD

**Issue by philippe-tc** [Ernst79/degree-days#9]
If I may make a suggestion for 'product improvement':

Create an option to use the results of a kWh meter instead of the gas meter for consumers of a heat pump.

**Comment by Wimll** [comment]
Did someone already make a fork of this repo to support this?

**Comment by Ernst79** [comment]
Since I've got my own heatpump installed last summer, this request became more urgent to me :smile Working on it now.

**Comment by Ernst79** [comment]
You can test it with 1.0.1-beta. After updating it, enable the option in the degree days options

**Comment by philippe-tc** [comment]
Sorry, can’t find how to enable the beta.
Can you give me a hint?

**Comment by philippe-tc** [comment]
Sorry, found it, but after reading your warming I’ll wait for the stable version.

**Comment by nelbs** [comment]
> Sorry, can’t find how to enable the beta. Can you give me a hint?

HACS >>> Degree-days integration >>> redownload >> enable "show beta versions"

**Comment by Ernst79** [comment]
Released as 1.0.1
